/*
 * AUTOGENERATED — DO NOT EDIT MANUALLY
 * Source CSV: rejestry_ME300_Version2.csv
 * CSV SHA256: <put-csv-sha256-here>
 */
#pragma once
#include <stdint.h>

namespace ME300 {

// Kanoniczne nazwy (bez prefiksu REG_)
static constexpr uint16_t CONTROL_WORD            = 0x2000; // Control Word (R/W)
static constexpr uint16_t SET_FREQUENCY_CONTROL   = 0x2001; // Set Frequency (control) (R/W) 0.01 Hz
static constexpr uint16_t CONTROL_FAULT_FLAGS     = 0x2002; // Control / Fault Flags (R/W, bit-dependent)

static constexpr uint16_t WARNING_ALARM_CODE      = 0x2100; // Warning / Alarm Code (R/O)
static constexpr uint16_t DRIVE_STATUS_BASIC      = 0x2101; // Drive Status (basic) (R/O)
static constexpr uint16_t SET_FREQUENCY_REPORTED  = 0x2102; // Set Frequency (reported) (R/O) 0.01 Hz
static constexpr uint16_t OUTPUT_FREQUENCY        = 0x2103; // Output Frequency (R/O) 0.01 Hz
static constexpr uint16_t OUTPUT_CURRENT          = 0x2104; // Output Current (R/O)
static constexpr uint16_t DC_BUS_VOLTAGE          = 0x2105; // DC Bus Voltage (R/O) 0.1 V
static constexpr uint16_t OUTPUT_VOLTAGE          = 0x2106; // Output Voltage (R/O) 0.1 V

// Alias z prefiksem REG_ (na potrzeby istniejącego kodu po zamianie)
static constexpr uint16_t REG_CONTROL_WORD            = CONTROL_WORD;
static constexpr uint16_t REG_SET_FREQUENCY_CONTROL   = SET_FREQUENCY_CONTROL;
static constexpr uint16_t REG_CONTROL_FAULT_FLAGS     = CONTROL_FAULT_FLAGS;

static constexpr uint16_t REG_WARNING_ALARM_CODE      = WARNING_ALARM_CODE;
static constexpr uint16_t REG_DRIVE_STATUS_BASIC      = DRIVE_STATUS_BASIC;
static constexpr uint16_t REG_SET_FREQUENCY_REPORTED  = SET_FREQUENCY_REPORTED;
static constexpr uint16_t REG_OUTPUT_FREQUENCY        = OUTPUT_FREQUENCY;
static constexpr uint16_t REG_OUTPUT_CURRENT          = OUTPUT_CURRENT;
static constexpr uint16_t REG_DC_BUS_VOLTAGE          = DC_BUS_VOLTAGE;
static constexpr uint16_t REG_OUTPUT_VOLTAGE          = OUTPUT_VOLTAGE;

} // namespace ME300